name: action-update-version
description: This Github Action automatically updates the versions of your repositories
runs:
  using: docker
  image: docker://outcomeco/action-update-version:2.0.1
  args:
    - 'bump'
